***Method 1***

SELECT CASE
    WHEN N NOT IN (SELECT DISTINCT P FROM BST WHERE P IS NOT NULL) THEN CONCAT(N, ' Leaf')
    WHEN P IS NULL THEN CONCAT(N, ' Root')
    ELSE concat(N, ' Inner')
END
FROM BST
ORDER BY N;

***Method 2***
SELECT N, 
CASE
    WHEN N NOT IN (SELECT DISTINCT P FROM BST WHERE P IS NOT NULL) THEN ' Leaf'
    WHEN P IS NULL THEN ' Root'
    ELSE ' Inner'
END
FROM BST
ORDER BY N;
